name: MagicBungee
version: ${project.version}
authors: [NathanWolf]
main: com.elmakers.mine.bukkit.bungee.MagicBungeePlugin
commands:
    mserver:
        description: "Moves a player to another server"
        usage: "mserver <player> <server>"
        permission: Magic.commands.mserver
permissions:
  Magic.commands.mserver:
    description: Player may sender players to other servers
    type: boolean
    default: op